import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import custom from '../styles/custom.css';

// import Script from 'next/script'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="Next , hunting coder , coder, hunting blog"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contact</li>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coders</h1>
        <p className={styles.description}>A blog for hunting coders by a hunting coder</p>
        <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript is the login used to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript is the login used to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript is the login used to design logic for the web</p>
          </div>
        </div>
      </main>
    </div>
  );
}
