import React from 'react'
import styles from "styles/Home.module.css";
import Link from 'next/link';
import Head from 'next/head';

const Navbar = () => {
  return (
    <>
        <Head>
            <title>Hunting Coder</title>
            <meta name="description" content="Generated by create next app" />
            <meta
            name="keywords"
            content="Next , hunting coder , coder, hunting blog"
            />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
      <nav className={styles.mainnav}>
        <ul>
          <Link href='/'><li>Home</li></Link>
          <Link href='/about'><li>About</li></Link>
          <Link href='/blog'><li>Blog</li></Link>
          <Link href='/contact'><li>Contact</li></Link>
        </ul>
      </nav>
    </>
  )
}

export default Navbar
